exclude: |
  (?x)(
      ^migrations/|
      ^tests_locust/|
      ^.git/|
      ^venv/|
      ^pipeline/|
      ^.idea/|
      ^.vscode|
      ^dvs_packages/__init__.py
  )
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-added-large-files

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: master
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
