name: Workflow to Deploy

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 radon
        python -V
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Test code
      run: flake8 --max-line-length=120